FORMAT: 1A
HOST: http://pizza.dev/api/v1

# PizzaAPI - Document

**Root URL** `http://pizza.dev/api/v1`

<!-- include(parts/intro.md) -->

<!-- include(parts/group-auth.md) -->

<!-- include(parts/group-order.md) -->

<!-- include(parts/group-pizza.md) -->

